### Numpy Array Operations

In [2]:
import numpy as np

In [3]:
# Slicing
arr = np.arange(1,12)
print("Basic Slicing: ",arr[2:8])
print("Step: ",arr[4:8:2])
print("Negative: ",arr[-3])

Basic Slicing:  [3 4 5 6 7 8]
Step:  [5 7]
Negative:  9


In [4]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element: ",arr2d[1 , 2])
print("Entire row: ",arr2d[1 , :])
print("Entire column: ",arr2d[: ,0])

Specific element:  6
Entire row:  [4 5 6]
Entire column:  [1 4 7]


### Sorting

In [5]:
unsorted1d = np.array([3,1,6,7,2,5,4])
print("Sorted 1D array: ",np.sort(unsorted1d))

unsorted2d = np.array([[5,2,1],[8,3,6],[3,2,5]])
print("Sorted 2D array(Columns): \n",np.sort(unsorted2d, axis=0))
print("Sorted 2D array(Rows): \n",np.sort(unsorted2d, axis=1))

Sorted 1D array:  [1 2 3 4 5 6 7]
Sorted 2D array(Columns): 
 [[3 2 1]
 [5 2 5]
 [8 3 6]]
Sorted 2D array(Rows): 
 [[1 2 5]
 [3 6 8]
 [2 3 5]]


### Filter

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2 == 0]
print("Filtered Array: ",even_numbers)

Filtered Array:  [ 2  4  6  8 10]


### Filter with Mask

In [7]:

mask = numbers>5
arrays = numbers[mask]
print("Using mask",arrays)

Using mask [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [ ]:
# [1,2,3,4,5,6,7,8,9,10]
indices = [1,2,4]
print(numbers[indices])

# Difference between mask and where is mask first converts into boolean array 
# for the specified condition and in where we get the values of the array indices directly
where_result = np.where(numbers>5) 
# It is returning indices
print(numbers[where_result])

where_result = np.where(numbers>5,100, 0) 
# first parameter is condition , second is if it true, third is else condition
# It is directly returning values
print(where_result)

[2 3 5]
[ 6  7  8  9 10]
[  0   0   0   0   0 100 100 100 100 100]


### Adding and Removing Array

In [9]:
arr1 = np.array((1,2,3))
arr2 = np.array((4,5,6))
print("Addition of 2 Arrays: \n",arr1+arr2)
print("Concatenated Array: \n",np.concatenate((arr1 ,arr2)))

Addition of 2 Arrays: 
 [5 7 9]
Concatenated Array: 
 [1 2 3 4 5 6]


### Compatibility

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Compatibility of the shapes is",a.shape == b.shape)

Compatibility of the shapes is True


In [12]:
original = np.array([1,2,3])
arr1 = np.array([4,5,6])
print("Rows are Added:\n", np.vstack((original,arr1)))

print("Columns are Added:\n", np.hstack((original,arr1)))

Rows are Added:
 [[1 2 3]
 [4 5 6]]
Columns are Added:
 [1 2 3 4 5 6]
