### `Numpy` tutorial with Chai and Code

In [2]:
import numpy as np

### Creating array from list

In [3]:
arr_1D = np.array([1,2,3,4,5])
print(arr_1D)

arr_2D = np.array([[1,2,3],[4,5,6]])
print(arr_2D)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Nump Array vs List

In [4]:
py_list = [1,2,3]
print(py_list*2) # list gets doubled

np_arr = np.array([1,2,3])
print(np_arr*2) # Each element gets multiplied with 2

# numpy array's execution is faster than a python list operation

[1, 2, 3, 1, 2, 3]
[2 4 6]


### Ways to Create different types of arrays/matrix

In [5]:
# There is a function to create array to create zero matrix
zeroes = np.zeros((3,5))
print(zeroes)

# There is a function to create array to create ones matrix
ones = np.ones((3,5))
print("\n",ones)

# There is a function to create array to create matrix with any desired constant value
full = np.full((2,3), 7)
print("\n", full)

# There is a function to create array to create matrix with random values
random= np.random.random((2,3))
print("\n", random)

# There is a function to create array to create matrix in a particular range with start, stop, jump value
sequence = np.arange(0 ,10 ,2)
print("\n", sequence)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[7 7 7]
 [7 7 7]]

 [[0.24666678 0.9659201  0.25549485]
 [0.32787614 0.54444876 0.7806239 ]]

 [0 2 4 6 8]


### Vectors, Matrix and Tensor

In [6]:
# 1D array is known as Vector
Vector = np.array([1,2,3])
print(Vector)

# 2D array is known as Matrix
Matrix = np.array([[1,2,3],[4,5,6]])
print("\n",Matrix)

# 3D array is known as Tensor
Tensor = np.array([[[1,2,3],[4,5,6]], 
                   [[7,8,9],[10,11,12]]
                   ])
print("\n",Tensor)

[1 2 3]

 [[1 2 3]
 [4 5 6]]

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Properties of Array

In [7]:
# The most important thing about numpy array is that it is made to work on similar group of data, it is optimized for that
array = np.array([[1,2,3],[4,5,6]])

print(array.shape)
print(array.size)
print(array.ndim)
print(array.dtype)

(2, 3)
6
2
int64


### Array Reshaping

In [10]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape((3,4))
print("\n",reshaped)

flattened = arr.flatten()
print("\n",flattened)

# Returns view instead of copy same as flatten but only difference ravel tries not to create the copy 
raveled = arr.ravel()
print("\n",raveled)

transpose = reshaped.T
print("\n",transpose)


[ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
