### Advance Operations with Business Example

In [ ]:
import numpy as np

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

In [8]:
print("=== Zomato Sales Analysis ===")
print("Shape of the data is",sales_data.shape)
print("Sample data for the 1st three resturant\n",sales_data[:, 1:])

=== Zomato Sales Analysis ===
Shape of the data is (5, 5)
Sample data for the 1st three resturant
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [10]:
# Total Sales Per Year
print("Sales per year:\n " , np.sum(sales_data, axis=0))
# Yearly Total
yearly_total = np.sum(sales_data[: , 1:], axis=1)
print("Yearly Total\n",np.sum(yearly_total))
print("Paradise Biryani:\n", np.sum(sales_data[0, 1:]))

Sales per year:
  [     15  810000  945000 1085000 1240000]
Yearly Total
 4080000
Paradise Biryani:
 800000


In [ ]:
# Minimum sales per restaurant
min = np.min(sales_data[: , 1:], axis=1)
print(min)
# Maximum sales per year
max = np.max(sales_data[: , 1:], axis=0)
print(max)
# Average sales per restaurant
mean = np.mean(sales_data[: , 1:] , axis= 1)
print(mean)
# Cumulative sales - adding previous values to coming one
cumsum = np.cumsum(sales_data[: ,1:], axis=1)
print(cumsum)

[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]
[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [ ]:
# Dot product
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(vector1 + vector2)
print(np.dot(vector1,vector2))
print(vector1*vector2)

print("Angle", np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2))))

[5 7 9]
32
[ 4 10 18]
Angle 0.2257261285527342


In [ ]:
# Vectorize Methods
food = np.array(["Chowmien", "Burger" , "Pizza"])
vectorize = np.vectorize(str.upper)
print(vectorize(food))

# if you multiply, add, divide a vector with a scalar then 
# it get applies to all element in the vector

['CHOWMIEN' 'BURGER' 'PIZZA']
